#!/usr/bin/env bash
# =============================================================================
#  configure_network.sh  (STEP 7)  --  ROS 2 / CycloneDDS network setup
#  * persists ROS_DOMAIN_ID / RMW / CYCLONEDDS_URI in ~/.bashrc (idempotent)
#  * regenerates cyclonedds.xml from env.sh (interface + Pi peer)
#  * applies kernel socket-buffer tuning for big camera streams (sudo)
#  * optionally brings up the wired NIC with a static IP (--setup-eth)
# =============================================================================
source "$(dirname "$0")/lib/common.sh"
require_not_root

print_config

# ---- 1. persist ROS/DDS env in ~/.bashrc (single managed block) -------------
BASHRC="$HOME/.bashrc"
MARK_BEGIN="# >>> EV-ROBOT ROS2 ENV >>>"
MARK_END="# <<< EV-ROBOT ROS2 ENV <<<"
step "Persisting ROS 2 environment in ~/.bashrc"
# remove any previous managed block, then append a fresh one (idempotent)
if grep -qF "$MARK_BEGIN" "$BASHRC" 2>/dev/null; then
  sed -i "/$(printf '%s' "$MARK_BEGIN" | sed 's/[][\/.*^$]/\\&/g')/,/$(printf '%s' "$MARK_END" | sed 's/[][\/.*^$]/\\&/g')/d" "$BASHRC"
fi
cat >> "$BASHRC" <<EOF
${MARK_BEGIN}
source /opt/ros/${ROS_DISTRO}/setup.bash
export ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
export ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
export RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
export CYCLONEDDS_URI=file://${PROJECT_DIR}/config/cyclonedds/cyclonedds.xml
[ -f ${ISAAC_ROS_WS}/install/setup.bash ] && source ${ISAAC_ROS_WS}/install/setup.bash
${MARK_END}
EOF
ok "wrote managed ROS2 env block (ROS_DOMAIN_ID=${ROS_DOMAIN_ID}, RMW=${RMW_IMPLEMENTATION})"

# ---- 2. regenerate cyclonedds.xml from env ----------------------------------
step "Generating CycloneDDS config for interface '${ROS_IFACE}', peer '${PI_IP}'"
XML="${PROJECT_DIR}/config/cyclonedds/cyclonedds.xml"
cat > "$XML" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by configure_network.sh from env.sh. Edit env.sh + re-run. -->
<CycloneDDS xmlns="https://cdds.io/config"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
  <Domain id="any">
    <General>
      <Interfaces>
        <NetworkInterface name="${ROS_IFACE}" priority="default" multicast="default"/>
      </Interfaces>
      <AllowMulticast>true</AllowMulticast>
      <MaxMessageSize>65500B</MaxMessageSize>
      <FragmentSize>4000B</FragmentSize>
    </General>
    <Discovery>
      <ParticipantIndex>auto</ParticipantIndex>
      <MaxAutoParticipantIndex>30</MaxAutoParticipantIndex>
      <Peers>
        <Peer address="${PI_IP}"/>
      </Peers>
    </Discovery>
    <Internal>
      <SocketReceiveBufferSize min="10MB"/>
      <Watermarks><WhcHigh>2MB</WhcHigh></Watermarks>
      <MultipleReceiveThreads enabled="true"/>
    </Internal>
    <Tracing><Verbosity>warning</Verbosity><OutputFile>stderr</OutputFile></Tracing>
  </Domain>
</CycloneDDS>
EOF
ok "wrote ${XML}"

# ---- 3. kernel socket buffers for big image streams (sudo) ------------------
step "Applying kernel socket-buffer tuning for DDS image streams"
ensure_sudo
sudo tee /etc/sysctl.d/60-cyclonedds.conf >/dev/null <<'EOF'
# Larger UDP buffers for Cyclone DDS carrying RealSense color/depth over GbE
net.core.rmem_max=33554432
net.core.rmem_default=16777216
net.core.wmem_max=33554432
net.core.wmem_default=16777216
net.ipv4.ipfrag_time=3
net.ipv4.ipfrag_high_thresh=134217728
EOF
sudo sysctl -q --system >/dev/null 2>&1 || sudo sysctl -p /etc/sysctl.d/60-cyclonedds.conf >/dev/null
ok "socket buffers raised (rmem_max=32MB)"

# ---- 4. optional: static IP on the wired NIC --------------------------------
if [[ "${1:-}" == "--setup-eth" ]]; then
  step "Configuring static IP ${LAPTOP_IP}/${LAPTOP_CIDR} on ${ROS_IFACE} (NetworkManager)"
  if need_cmd nmcli && ip link show "${ROS_IFACE}" >/dev/null 2>&1; then
    sudo nmcli connection delete "robot-${ROS_IFACE}" 2>/dev/null || true
    sudo nmcli connection add type ethernet ifname "${ROS_IFACE}" con-name "robot-${ROS_IFACE}" \
         ipv4.method manual ipv4.addresses "${LAPTOP_IP}/${LAPTOP_CIDR}" ipv4.never-default yes
    sudo nmcli connection up "robot-${ROS_IFACE}"
    ok "${ROS_IFACE} up at ${LAPTOP_IP}/${LAPTOP_CIDR} (never-default: won't override your internet route)"
  else
    warn "nmcli or ${ROS_IFACE} unavailable; bring the link up manually."
  fi
fi

# ---- 5. VPN warning ---------------------------------------------------------
if ip route | grep -qE '(^| )0\.0\.0\.0/1 .*tun0|(^| )default .*tun0'; then
  warn "ExpressVPN (tun0) is capturing the default route -> DDS discovery to the Pi WILL FAIL."
  warn "Disconnect the VPN (or enable split tunneling) before robot bringup."
fi

step "STEP 7 complete"
warn "Open a NEW terminal (or 'source ~/.bashrc') so the env takes effect."
